if(ENABLE_UNITTESTS)
  include(GtestTools)
  if(GTest_FOUND)
    add_subdirectory(unit)
  endif()
endif()

if(ENABLE_FORMAT_CHECK)
  include(FormatTools)
  if(NOT CLANG_FORMAT_EXE)
    message(WARNING "Clang-Format not found; FormatCheck is unavailable.")
  endif()
endif()

if(ENABLE_TIDY_CHECK)
  include(TidyTools)
  if(NOT CLANG_TIDY_EXE OR NOT Python3_Interpreter_FOUND)
    message(WARNING "Clang-Tidy or Python 3 not found; TidyCheck is unavailable.")
  endif()
endif()

if((ENABLE_FORMAT_CHECK AND CLANG_FORMAT_EXE) OR
   (ENABLE_TIDY_CHECK AND CLANG_TIDY_EXE AND Python3_Interpreter_FOUND))
  add_subdirectory(static)
endif()
